micronaut:
  application:
    name: swagger-java
  server:
    port: 8087
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
